[package]
name = "liars-dice"
version = "0.1.0"
edition = "2024"

[dependencies]
game-engine = { path = "../game-engine" }
game-core = { path = "../game-core" }
anyhow = "1.0.100"
inquire = "0.9.1"
colored = "3.0.0"
rand = "0.9.2"
